### ISSUE TITLE
fail safe install - tsb error examples

### ISSUE THREAD

**Issue by dom3d** [TypeScriptBuilder/tsb#48]
This might be related to my system (I guess tsb didn't install properly. Had to do a 'npm cache clean' first). I have the error output below if I do the following steps

- create and go into a new folder
- git init   OR    touch test.ts
- tsb

"
Dashboard at http://localhost:4444
CHILD ERR STDERR: /usr/local/lib/node_modules/tsb/src/server/workers/fileListing/fileListingWorker.js:25
                .filter(function (x) { return !x.includes('/.git/'); })
                                                 ^
TypeError: undefined is not a function
    at /usr/local/lib/node_modules/tsb/src/server/workers/fileListing/fileListingWorker.js:25:50
    at Array.filter (native)
    at sendNewFileList (/usr/local/lib/node_modules/tsb/src/server/workers/fileListing/fileListingWorker.js:25:18)
    at /usr/local/lib/node_modules/tsb/src/common/utils.js:88:27
    at EventEmitter.fileAdded (/usr/local/lib/node_modules/tsb/src/server/workers/fileListing/fileListingWorker.js:53:17)
    at EventEmitter.emit (events.js:110:17)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/tsb/node_modules/chokidar/index.js:169:15)
    at EventEmitter.FSWatcher._emit (/usr/local/lib/node_modules/tsb/node_modules/chokidar/index.js:206:5)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/tsb/node_modules/chokidar/lib/fsevents-handler.js:288:12)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/tsb/node_modules/chokidar/lib/fsevents-handler.js:331:11)

ts worker restarting. Don't know why it stopped with code: 1
"

**Comment by dom3d** [comment]
In the browser I have a blank page and the following issue:

Uncaught TypeError: o.commandName.split is not a function

**Comment by basarat** [comment]
I tried the process as mentioned. No errors : 

![image](https://cloud.githubusercontent.com/assets/874898/11610882/8c158686-9c05-11e5-84a3-eb722039eeb8.png)

Suspect the version on NPM is broken. Making a new release :rose:

**Comment by basarat** [comment]
Pushed to NPM : https://github.com/TypeScriptBuilder/tsb/releases/tag/v1.1.1 :rose:

**Comment by basarat** [comment]
In fact I am going to make the NPM version non functional and more informative if the true status : https://github.com/TypeScriptBuilder/tsb/issues/49
